### ISSUE TITLE
Can you show me how to train decoder-1-700.ckpt and encoder-1-700.ckpt?

### ISSUE THREAD

**Issue by Kyfafyd** [bit-slave/MirrorGAN_Reproduction#2]
Thanks very much!

**Comment by Haoliang-rp** [comment]
Hi, it is pre-trained on AttnGAN. You can find their repository here https://github.com/taoxugit/AttnGAN.

**Comment by Kyfafyd** [comment]
Thanks very much for reply!

I know that text_encoder.pth and image_encoder.pth are pretrained on AttnGAN. But I wonder how to train decoder-1-700.ckpt and encoder-1-700.ckpt?

Thanks very much!



-----原始邮件-----
发件人:Haoliang <notifications@github.com>
发送时间:2020-03-14 22:45:33 (星期六)
收件人: Haoliang-rp/MirrorGAN_Reproduction <MirrorGAN_Reproduction@noreply.github.com>
抄送: Kyfafyd <Kyfafyd@zju.edu.cn>, Author <author@noreply.github.com>
主题: Re: [Haoliang-rp/MirrorGAN_Reproduction] Can you show me how to train decoder-1-700.ckpt and encoder-1-700.ckpt? (#2)






Hi, it is pre-trained on AttnGAN. You can find their repository here https://github.com/taoxugit/AttnGAN.

**Comment by Haoliang-rp** [comment]
Hi, the decoder-1-700 and encoder-1-700 are actually trained on https://github.com/yunjey/pytorch-tutorial/tree/master/tutorials/03-advanced/image_captioning.

**Comment by Kyfafyd** [comment]
Thanks very much.

But I wonder how you preprocess data for training, especially json file(captions). I have been confused for some time.


-----原始邮件-----
发件人:Haoliang <notifications@github.com>
发送时间:2020-03-14 23:31:37 (星期六)
收件人: Haoliang-rp/MirrorGAN_Reproduction <MirrorGAN_Reproduction@noreply.github.com>
抄送: Kyfafyd <Kyfafyd@zju.edu.cn>, Author <author@noreply.github.com>
主题: Re: [Haoliang-rp/MirrorGAN_Reproduction] Can you show me how to train decoder-1-700.ckpt and encoder-1-700.ckpt? (#2)






Hi, the decoder-1-700 and encoder-1-700 are actually trained on https://github.com/yunjey/pytorch-tutorial/tree/master/tutorials/03-advanced/image_captioning.

**Comment by Haoliang-rp** [comment]
Hi, the preprocessed bird dataset provided in the original repo of MirroGAN could be used as the reference. It should be compatible with the data loader in the image captioning model.

**Comment by Kyfafyd** [comment]
Thanks, I actually know that.

But I have been trying to preprocess a json file(refer to coco dataset). After that, the problem went into an error like this.



-----原始邮件-----
发件人:Haoliang <notifications@github.com>
发送时间:2020-03-15 00:04:12 (星期日)
收件人: Haoliang-rp/MirrorGAN_Reproduction <MirrorGAN_Reproduction@noreply.github.com>
抄送: Kyfafyd <Kyfafyd@zju.edu.cn>, Author <author@noreply.github.com>
主题: Re: [Haoliang-rp/MirrorGAN_Reproduction] Can you show me how to train decoder-1-700.ckpt and encoder-1-700.ckpt? (#2)






Hi, the preprocessed bird dataset provided in the original repo of MirroGAN could be used as the reference. It should be compatible with the data loader in the image captioning model.

**Comment by Kyfafyd** [comment]
I have found problem, thanks!
